### ISSUE TITLE
Notice regarding org.kde.Platform branch 5.15-22.08 being end-of-life

### ISSUE THREAD

**Issue by Tractor777** [flathub/com.github.iwalton3.jellyfin-media-player#41]
Not a bug, but unsure where else to raise it: as per the title, Ubuntu 24.04 beta and Jellyfin Flatpak gives a notice about:

Info: runtime org.kde.Platform branch 5.15-22.08 is end-of-life, with reason:
   We strongly recommend moving to the latest Qt 5.15-based stable version of the Platform and SDK
Info: applications using this runtime:
   com.github.iwalton3.jellyfin-media-player

**Comment by kenden** [comment]
Maybe these lines
https://github.com/flathub/com.github.iwalton3.jellyfin-media-player/blob/master/com.github.iwalton3.jellyfin-media-player.json#L4
https://github.com/flathub/com.github.iwalton3.jellyfin-media-player/blob/master/com.github.iwalton3.jellyfin-media-player.json#L7
could be updated to version `6.4.2` (the version from: https://flathub.org/apps/io.qt.qtwebengine.BaseApp ) ?

**Comment by applemayexist** [comment]
Until the port to Qt 6 is finished, they should just be changed to `5.15-23.08` which is what [this PR](https://github.com/flathub/com.github.iwalton3.jellyfin-media-player/pull/24) does.

**Comment by Tractor777** [comment]
I ran an update today and the error message has gone away, so I guess that the package has been updated?

**Comment by kenden** [comment]
The PR mentioned 2 comments above was merged, yes.
I think this issue can be closed now.
