### ISSUE TITLE
MPV background config option no longer works after 1.10.0 update, Flatpak Specific 

### ISSUE THREAD

**Issue by Tracenji** [flathub/com.github.iwalton3.jellyfin-media-player#48]
i use the MPV config option **_background=#D0D0D0_** to reduce uneven wear on my oled monitor
after updating to version 1.10.0, this option no longer works, tried with mpv.conf and the Manual MPV Configuration in client settings

this seems to be a Flatpak only issue, as if i install the debian bookworm version of 1.10.0 in distrobox, the background option works as expected 
other MPV options may be affected as well, i have not tested any other options

**Comment by Tracenji** [comment]
my bad, **_background_** has been renamed to **_background-color_** as of MPV v0.38.0

**Comment by francoism90** [comment]
@Tracenji Where did you put the config file?
